config/routes.rb
Rails.application.routes.draw do
  resources :projects

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users

	get '/join_project/:id', to: 'users#join_project', as: 'join_project'

  root to: 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
	belongs_to :user

	validates :category, :description, :zone, :name, :start_date, :end_date, presence: true

	searchable do
		text :name, :description, :zone, :category
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	skip_before_action :authenticate_user!, only: [:index, :show]  
	before_action :set_project, only: [:show, :edit, :update, :destroy, :validate_creator]
	before_action :validate_creator, only: [:edit, :destroy]

  # GET /projects
  # GET /projects.json
  def index
		@search = Project.search do
			fulltext params[:search]
		end    
		@projects = @search.results
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
		@user = User.find(@project.creator)
		@total = ProjectsUser.where(project_id: @project.id).count
		@followers = User.select("users.id, users.name, users.email").joins("JOIN projects_users ON projects_users.user_id = users.id").where("projects_users.project_id = ?", @project.id)
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create    
		@project = Project.new(project_params)
		@project.creator = current_user.id

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy   
		@project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
		def validate_creator
			unless current_user.id == @project.creator
				redirect_to root_url, alert: "No tienes los permisos necesarios" 
			end
		end

    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:category, :description, :zone, :name, :target, :start_date, :end_date, :picture)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="form-group">
		<%= f.label :categoría %><br>
		<%= f.select :category, options_for_select(['Propuesta de ley', 'Petición ciudadana', 'Acción social']), :prompt => true, class: 'form-control' %>
	</div>
	
  <div class="form-group">
    <%= f.label :zona %><br>
    <%= f.select :zone, options_for_select(['Álvaro Obregón', 'Azcapotzalco', 'Benito Juárez', 'Cuajimalpa', 'Coyoacán', 'Cuauhtemoc', 'Gustavo A. Madero', 'Iztacalco', 'Iztapalapa', 'Magdalena Contreras', 'Miguel Hidalgo', 'Milpa Alta', 'Tláhuac', 'Tlalpan', 'Venustiano Carranza', 'Xochimilco']), :prompt => true, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :nombre %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
	<div class="form-group">
    <%= f.label :descripción %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :meta_de_agentes_de_cambio %><br>
    <%= f.number_field :target, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :fecha_de_inicio %><br>
    <%= f.date_select :start_date, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :fecha_de_fin %><br>
    <%= f.date_select :end_date, class: 'form-control' %>
  </div>
	<div class="form-group">
		<%= f.label :imagen %><br>
		<%= f.file_field :picture, class: 'btn' %>
	</div>
  <div class="actions">
    <%= f.submit "Crear", class: 'btn btn-primary btn-md' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<%= form_tag projects_path, :method => :get do %>
  <div class="form-group">
		<div class="col-md-10">
    	<%= text_field_tag :search, params[:search], class: 'form-control' %>
		</div>
		<div class="col-md-2">
    	<%= submit_tag "Search", :name => nil , :class => 'btn btn-default' %>
		</div>
  </div>
<% end %>
<br><br>

<h1>Causas</h1>

<ul class="thumbnails">
	<div class="row">
	<% @projects.each do |project| %>  
		<div class="col-md-3">
		  <div class="thumbnail">
				<%= image_tag(project.picture_url, :size => '300x200') if project.picture.present? %>
		    <h3>
					<%= link_to project.name, project, class: 'btn-link' %>
				</h3>
		    <p>
					<%= project.description %>
				</p>
		  </div>
		</div>
	<% end %>
	</div>
</ul>

<br>

<%= link_to 'New Project', new_project_path, class: 'btn btn-primary btn-lg' %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<div class="row">
	<div class="page_header">
		<h1><%= @project.name %><br><small><%= @total %> seguidores </small></h1>
	</div>

	<% if user_signed_in? %>
		<% if current_user.id == @project.creator %>	
			<%= link_to 'Edit', edit_project_path(@project), class: 'btn btn-link btn-lg' %>
		<% end %>
		<% unless current_user.id == @project.creator %>
			<%= link_to 'Únete', join_project_path(@project), class: 'btn btn-primary btn-large' %>
		<% end %>
	<% end %>
</div>
<br>

<p>
	<%= image_tag(@project.picture_url, :size => "300x200", :class => "img-responsive img-hover") if @project.picture.present? %>
</p>

<table class="table">
  <tbody>
      <tr>
        <td><strong>Líder de la causa:</strong></td>
        <td><%= link_to @user.name, @user, class: 'btn-link' %></td>
      </tr>
			<tr>
        <td><strong>Categoría:</strong></td>
        <td><%= @project.category %></td>
      </tr>
			<tr>
        <td><strong>Zona:</strong></td>
        <td><%= @project.zone %></td>
      </tr>
			<tr>
        <td><strong>Descripción:</strong></td>
        <td><%= @project.description %></td>
      </tr>
			<tr>
        <td><strong>Meta de agentes de cambio:</strong></td>
        <td><%= @project.target %></td>
      </tr>
			<tr>
        <td><strong>Fecha de inicio:</strong></td>
        <td><%= @project.start_date %></td>
      </tr>
			<tr>
        <td><strong>Fecha de fin:</strong></td>
        <td><%= @project.end_date %></td>
      </tr>
  </tbody>
</table>

<br><br>

<h4>Usuarios que se han unido</h4>

<table class="table">
  <tbody>
    <% @followers.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<br>